### ISSUE TITLE
pwm pulse需要先失能再使能才能更改生效

### ISSUE THREAD

**Issue by Ghazigq** [flyingcys/rt-thread#37]
使用pinname_whitelist_pwm5 SD1_D2做为输出引脚
使用命令pwm控制
```
    pwm probe pwm1
    pwm set 5 10000000 5000000
    pwm enable 5
```
此时使用逻辑分析仪查看输出正常
```
    pwm set 5 10000000 1000000
```
更改后，逻辑分析仪上查看仍保持不变，使用disable enable重新开关一次后即可正生效

**Comment by unicornx** [comment]
每次重新 set 的话，是需要把上次的disable ，再 enable 才能使能新的的。这是目前 pwm controller 的要求，请问你提这个 issue 的问题是什么？

**Comment by Ghazigq** [comment]
> 每次重新 set 的话，是需要把上次的disable ，再 enable 才能使能新的的。这是目前 pwm controller 的要求，请问你提这个 issue 的问题是什么？

我以为是个bug呢
